import Head from "next/head";

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen shadow-md">
      <Head>
        <title>ChatCube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Icon.png" />
      </Head>
      <h1>I am the landing page</h1>
    </div>
  );
}
