import Head from "next/head";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import { db } from "../firebase";

export default function Home({ users }) {
  return (
    <div className="flex flex-col">
      <Head>
        <title>ChatCube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Sidebar users={users} />
    </div>
  );
}

export async function getServerSideProps() {
  const allusers = await db.collection("users").get();

  const users = allusers.docs.map((user) => ({
    id: user.id,
    ...user.data(),
    lastSeen: null,
  }));
  return {
    props: { users },
  };
}
